[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=root

[program:messenger-consume-email]
command=php /app/bin/console messenger:consume email --time-limit=600 --memory-limit=512M --limit=100 --failure-limit=5 --sleep=5 --no-reset
user=www-data
numprocs=%(ENV_DOCKER_MAUTIC_WORKERS_CONSUME_EMAIL)s
startsecs=0
autostart=true
autorestart=true
startretries=10
stopwaitsecs=30
stopsignal=TERM
stopasgroup=true
killasgroup=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:messenger-consume-hit]
command=php /app/bin/console messenger:consume hit --time-limit=600 --memory-limit=512M --limit=100 --failure-limit=5 --sleep=5 --no-reset
user=www-data
numprocs=%(ENV_DOCKER_MAUTIC_WORKERS_CONSUME_HIT)s
startsecs=0
autostart=true
autorestart=true
startretries=10
stopwaitsecs=30
stopsignal=TERM
stopasgroup=true
killasgroup=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:messenger-consume-failed]
command=php /app/bin/console messenger:consume failed --time-limit=600 --memory-limit=512M --limit=20 --failure-limit=5 --sleep=30 --no-reset
user=www-data
numprocs=%(ENV_DOCKER_MAUTIC_WORKERS_CONSUME_FAILED)s
startsecs=0
autostart=true
autorestart=true
startretries=10
stopwaitsecs=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[group:messenger]
programs=messenger-consume-email,messenger-consume-hit,messenger-consume-failed
priority=999